//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazer_Svit.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В корзину.
        /// </summary>
        public static string add_to_cart {
            get {
                return ResourceManager.GetString("add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Купить в 1 клик.
        /// </summary>
        public static string add_to_cart_click {
            get {
                return ResourceManager.GetString("add_to_cart_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        public static string cart_amount {
            get {
                return ResourceManager.GetString("cart_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ОФОРМИТЬ ЗАКАЗ.
        /// </summary>
        public static string cart_checkout {
            get {
                return ResourceManager.GetString("cart_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коризна пуста.
        /// </summary>
        public static string cart_empty {
            get {
                return ResourceManager.GetString("cart_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продукт.
        /// </summary>
        public static string cart_name {
            get {
                return ResourceManager.GetString("cart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string cart_price {
            get {
                return ResourceManager.GetString("cart_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоймость.
        /// </summary>
        public static string cart_total_item_price {
            get {
                return ResourceManager.GetString("cart_total_item_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая стоймость заказа.
        /// </summary>
        public static string cart_total_price {
            get {
                return ResourceManager.GetString("cart_total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес или Номер склад Новой Почты.
        /// </summary>
        public static string checkout_adress_adress {
            get {
                return ResourceManager.GetString("checkout_adress_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        public static string checkout_adress_city {
            get {
                return ResourceManager.GetString("checkout_adress_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес доставки.
        /// </summary>
        public static string checkout_adress_header {
            get {
                return ResourceManager.GetString("checkout_adress_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доставка не требуется.
        /// </summary>
        public static string checkout_adress_no_deliv {
            get {
                return ResourceManager.GetString("checkout_adress_no_deliv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Область.
        /// </summary>
        public static string checkout_adress_region {
            get {
                return ResourceManager.GetString("checkout_adress_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ подтверждаю.
        /// </summary>
        public static string checkout_confirm {
            get {
                return ResourceManager.GetString("checkout_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактные данные.
        /// </summary>
        public static string checkout_cont_header {
            get {
                return ResourceManager.GetString("checkout_cont_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эл. почта.
        /// </summary>
        public static string checkout_cont_mail {
            get {
                return ResourceManager.GetString("checkout_cont_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и фамилия.
        /// </summary>
        public static string checkout_cont_name {
            get {
                return ResourceManager.GetString("checkout_cont_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон.
        /// </summary>
        public static string checkout_cont_phone {
            get {
                return ResourceManager.GetString("checkout_cont_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ доставки.
        /// </summary>
        public static string checkout_deliv {
            get {
                return ResourceManager.GetString("checkout_deliv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г. Киев, проспект Леся Курбаса 2Б (здание завода “НВП Сатурн” ).
        /// </summary>
        public static string checkout_deliv_adress {
            get {
                return ResourceManager.GetString("checkout_deliv_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самовывоз.
        /// </summary>
        public static string checkout_deliv_myself {
            get {
                return ResourceManager.GetString("checkout_deliv_myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая почта.
        /// </summary>
        public static string checkout_deliv_post {
            get {
                return ResourceManager.GetString("checkout_deliv_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курьером Новой почты.
        /// </summary>
        public static string checkout_deliv_post_cour {
            get {
                return ResourceManager.GetString("checkout_deliv_post_cour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите ваш контактный номер, и мы перезвоним вам для уточнения деталей заказа.
        /// </summary>
        public static string checkout_details {
            get {
                return ResourceManager.GetString("checkout_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать заказ.
        /// </summary>
        public static string checkout_edit_order {
            get {
                return ResourceManager.GetString("checkout_edit_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Быстрый заказ.
        /// </summary>
        public static string checkout_fast {
            get {
                return ResourceManager.GetString("checkout_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформление заказа.
        /// </summary>
        public static string checkout_header {
            get {
                return ResourceManager.GetString("checkout_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить наличными.
        /// </summary>
        public static string checkout_pay_cash {
            get {
                return ResourceManager.GetString("checkout_pay_cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор способов доставки и оплаты.
        /// </summary>
        public static string checkout_pay_header {
            get {
                return ResourceManager.GetString("checkout_pay_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На карту Приват банка.
        /// </summary>
        public static string checkout_pay_pb_card {
            get {
                return ResourceManager.GetString("checkout_pay_pb_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить через Visa/Mastercard.
        /// </summary>
        public static string checkout_pay_visa_card {
            get {
                return ResourceManager.GetString("checkout_pay_visa_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Способ оплатиты.
        /// </summary>
        public static string checkout_pay_way {
            get {
                return ResourceManager.GetString("checkout_pay_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильный телефон.
        /// </summary>
        public static string checkout_tel {
            get {
                return ResourceManager.GetString("checkout_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите полный номер с региональным кодом. Например, 380935553535.
        ///Или +79610000000 для неукраинских номеров.
        /// </summary>
        public static string checkout_tel_info {
            get {
                return ResourceManager.GetString("checkout_tel_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        public static string checkout_total {
            get {
                return ResourceManager.GetString("checkout_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К оплате.
        /// </summary>
        public static string checkout_total_to_pay {
            get {
                return ResourceManager.GetString("checkout_total_to_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О компании.
        /// </summary>
        public static string contact_about {
            get {
                return ResourceManager.GetString("contact_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Киев.
        /// </summary>
        public static string contact_adress {
            get {
                return ResourceManager.GetString("contact_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на проспект Леся Курбаса, д. 2Б.
        /// </summary>
        public static string contact_adress_street {
            get {
                return ResourceManager.GetString("contact_adress_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить сообщение.
        /// </summary>
        public static string contact_button {
            get {
                return ResourceManager.GetString("contact_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожалуйста , заполните форму ниже и наша команда L.S свяжется с Вами в скорем времени.
        /// </summary>
        public static string contact_sub_header {
            get {
                return ResourceManager.GetString("contact_sub_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для этого просим добавить четкое описание Вашего проекта, втом числе пропишите необходимых материалы, размеры. Мы можем попросить Вас предоставить дополнительную информацию для качественного и быстрой реализации Вашей идеи. Не забудьте указать количество, тип или цвет, что Вы хотите..
        /// </summary>
        public static string contact_sub_info {
            get {
                return ResourceManager.GetString("contact_sub_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время работы офиса:.
        /// </summary>
        public static string contact_time_1 {
            get {
                return ResourceManager.GetString("contact_time_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пн- Пт: 10:00 - 19:00.
        /// </summary>
        public static string contact_time_2 {
            get {
                return ResourceManager.GetString("contact_time_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить файл.
        /// </summary>
        public static string contact_upload {
            get {
                return ResourceManager.GetString("contact_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лазерная резка и гравировка.
        /// </summary>
        public static string footer_copyright {
            get {
                return ResourceManager.GetString("footer_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша почта.
        /// </summary>
        public static string form_mail {
            get {
                return ResourceManager.GetString("form_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваше имя и фамилия.
        /// </summary>
        public static string form_name {
            get {
                return ResourceManager.GetString("form_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш номер телефона.
        /// </summary>
        public static string form_phone {
            get {
                return ResourceManager.GetString("form_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проставьте оценку:.
        /// </summary>
        public static string form_score {
            get {
                return ResourceManager.GetString("form_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст сообщения.
        /// </summary>
        public static string form_text {
            get {
                return ResourceManager.GetString("form_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наши телефоны.
        /// </summary>
        public static string header_phones {
            get {
                return ResourceManager.GetString("header_phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать ещё.
        /// </summary>
        public static string inst_button_text {
            get {
                return ResourceManager.GetString("inst_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string item_category {
            get {
                return ResourceManager.GetString("item_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string item_descr {
            get {
                return ResourceManager.GetString("item_descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы.
        /// </summary>
        public static string item_reviews {
            get {
                return ResourceManager.GetString("item_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Похожие товары.
        /// </summary>
        public static string items_similar {
            get {
                return ResourceManager.GetString("items_similar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ШИРОКИЙ АССОРТИМЕНТ МАТЕРИАЛОВ.
        /// </summary>
        public static string main_descr_header {
            get {
                return ResourceManager.GetString("main_descr_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - это уже не новая технология, но она приобрела новые возможности вместе с нашей дизайнерской студией «LS» в Киеве. Лазерная порезка позволяет разрезать или раскроить любой материал при помощи луча лазер высокой мощности. Компьютерное управление, аккуратные разрезы с низкой зоной термического воздействия позволяют выполнять работы любой сложности с точностью хирурга. Волшебному лучу поддается самый разный материал, как мягкий, так и сверх твердый..
        /// </summary>
        public static string main_desct_text_1 {
            get {
                return ResourceManager.GetString("main_desct_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - это высоко-точная передача вашей задумки на дерево, кожу, картон и т.д. Красота не имеет границ, как и рука человека, способная воплотить в реальность любой замысел дизайнера..
        /// </summary>
        public static string main_desct_text_2 {
            get {
                return ResourceManager.GetString("main_desct_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гравировка нанесенная лазером.
        /// </summary>
        public static string main_desct_text_gravir {
            get {
                return ResourceManager.GetString("main_desct_text_gravir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лазерная резка.
        /// </summary>
        public static string main_desct_text_lazer {
            get {
                return ResourceManager.GetString("main_desct_text_lazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акрил.
        /// </summary>
        public static string main_Example_1 {
            get {
                return ResourceManager.GetString("main_Example_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пластик.
        /// </summary>
        public static string main_Example_2 {
            get {
                return ResourceManager.GetString("main_Example_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Картон.
        /// </summary>
        public static string main_Example_3 {
            get {
                return ResourceManager.GetString("main_Example_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дерево.
        /// </summary>
        public static string main_Example_4 {
            get {
                return ResourceManager.GetString("main_Example_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фанера.
        /// </summary>
        public static string main_Example_5 {
            get {
                return ResourceManager.GetString("main_Example_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа и ткани.
        /// </summary>
        public static string main_Example_6 {
            get {
                return ResourceManager.GetString("main_Example_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИМЕРЫ РАБОТ.
        /// </summary>
        public static string main_examples_header {
            get {
                return ResourceManager.GetString("main_examples_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КАЧЕСТВЕННОЕ УКРАИНСКОЕ ОБОРУДОВАНИЕ.
        /// </summary>
        public static string main_reason_first_header {
            get {
                return ResourceManager.GetString("main_reason_first_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наше оборудование сделано Украинской молодой но успешной компанией . С применением новейших технологий и высоким качеством комплектующих.
        /// </summary>
        public static string main_reason_first_text {
            get {
                return ResourceManager.GetString("main_reason_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПОМОЩЬ С МАКЕТОМ.
        /// </summary>
        public static string main_reason_fourth_header {
            get {
                return ResourceManager.GetString("main_reason_fourth_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь в реализации идеи в макет. Мы приложим максимум усилий чтобы конечное изделие соответствовало Вашей задумке.
        /// </summary>
        public static string main_reason_fourth_text {
            get {
                return ResourceManager.GetString("main_reason_fourth_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИЧИНЫ ПОЧЕМУ ВЫБИРАЮТ НАС.
        /// </summary>
        public static string main_reason_header {
            get {
                return ResourceManager.GetString("main_reason_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СРОК ВЫПОЛНЕНИЯ ЗАКАЗА.
        /// </summary>
        public static string main_reason_second_header {
            get {
                return ResourceManager.GetString("main_reason_second_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость выполнения задачи от 1 часа до 7 дней крупные заказы.
        /// </summary>
        public static string main_reason_second_text {
            get {
                return ResourceManager.GetString("main_reason_second_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СКОРОСТЬ РЕЗКИ.
        /// </summary>
        public static string main_reason_third_header {
            get {
                return ResourceManager.GetString("main_reason_third_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Качество оборудования позволяет резать со средней скоростью около 25 мм/сек.
        /// </summary>
        public static string main_reason_third_text {
            get {
                return ResourceManager.GetString("main_reason_third_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lazer Svit.
        /// </summary>
        public static string main_title_b {
            get {
                return ResourceManager.GetString("main_title_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы - Дизайнерская студия.
        /// </summary>
        public static string main_title_h1 {
            get {
                return ResourceManager.GetString("main_title_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предоставляем услуги по порезке и гравировке материалов.
        /// </summary>
        public static string main_title_h2 {
            get {
                return ResourceManager.GetString("main_title_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акрил (оргстекло).
        /// </summary>
        public static string materials_acryl_header {
            get {
                return ResourceManager.GetString("materials_acryl_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акрил идеально подходит для лазерной резки, с обеих сторон он оснащен защитной пленкой , чтобы его поверхности были чистыми и без царапин. Лазерная режущая кромка также является абсолютно чистой, при лазерной гравировке создаеться гладкая матовая поверхность..
        /// </summary>
        public static string materials_acryl_text {
            get {
                return ResourceManager.GetString("materials_acryl_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы располагаем широким спектром материалов, которые идеально подходят для лазерной резки гравировки..
        /// </summary>
        public static string materials_header {
            get {
                return ResourceManager.GetString("materials_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наше оборудование может обрабатывать различные материалы, если у нас такого материала нету, вы можете отправить материал нам или привезти с собой в студию. Некоторые материалы, мы можем заказать специально для Вас. Если есть какие-либо материалы, которые вы хотели бы вырезать или выгравировать лазером или фрезером, пожалуйста, не стесняйтесь обращаться к нам по электронной почте и спрашивать, можем ли мы выполнить резку или гравировку материала..
        /// </summary>
        public static string materials_other_text {
            get {
                return ResourceManager.GetString("materials_other_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фанера.
        /// </summary>
        public static string materials_plywood_header {
            get {
                return ResourceManager.GetString("materials_plywood_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фанера прекрасная альтернатива дереву. Фанеру можно вскрыть или покрасить, она эластична. Мы используем самые качественные леса, которые отлично режутся нашим лазером. Все поверхности имеют качество первого сорта, край лазерной резки более темный, чем материал, но приятный. С помощью лазерной порезка фанеры можно достичь хороших и точных результатов. Неизменный плюс фанеры в сравнении с деревом — прочность, легкость и, конечно, цена..
        /// </summary>
        public static string materials_plywood_text {
            get {
                return ResourceManager.GetString("materials_plywood_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другие материалы.
        /// </summary>
        public static string materilas_other_header {
            get {
                return ResourceManager.GetString("materilas_other_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина.
        /// </summary>
        public static string menu_cart {
            get {
                return ResourceManager.GetString("menu_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оформление заказа.
        /// </summary>
        public static string menu_checkout {
            get {
                return ResourceManager.GetString("menu_checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string menu_contacts {
            get {
                return ResourceManager.GetString("menu_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лазерная порезка.
        /// </summary>
        public static string menu_lazer {
            get {
                return ResourceManager.GetString("menu_lazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация для заказа.
        /// </summary>
        public static string menu_lazer_info {
            get {
                return ResourceManager.GetString("menu_lazer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материалы.
        /// </summary>
        public static string menu_lazer_materials {
            get {
                return ResourceManager.GetString("menu_lazer_materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цены.
        /// </summary>
        public static string menu_lazer_price {
            get {
                return ResourceManager.GetString("menu_lazer_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string menu_main {
            get {
                return ResourceManager.GetString("menu_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары.
        /// </summary>
        public static string menu_products {
            get {
                return ResourceManager.GetString("menu_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отзывы клиентов.
        /// </summary>
        public static string menu_reviews {
            get {
                return ResourceManager.GetString("menu_reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УФ Печать.
        /// </summary>
        public static string menu_uv_header {
            get {
                return ResourceManager.GetString("menu_uv_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на грн..
        /// </summary>
        public static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация для заказа.
        /// </summary>
        public static string order_info_header {
            get {
                return ResourceManager.GetString("order_info_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Услуга дизайнера платная ее стоимость составляет от сложности работы и начинается— от 50 грн..
        /// </summary>
        public static string order_info_info {
            get {
                return ResourceManager.GetString("order_info_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если Вы решили самостоятельно, или при помощи дизайнера подготовить макет, тогда обратите внимание на такие моменты:.
        /// </summary>
        public static string order_info_subheader {
            get {
                return ResourceManager.GetString("order_info_subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы работаем в векторной программе.
        /// </summary>
        public static string order_info_text1 {
            get {
                return ResourceManager.GetString("order_info_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на в макете на порезку и гравировку не допускается наложение слоёв и двойных (и более) контуров..
        /// </summary>
        public static string order_info_text10 {
            get {
                return ResourceManager.GetString("order_info_text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для корректной и быстрого просчета стоимости, а также для производства заказа необходимо предоставить макет в векторе. Самые популярные форматы векторных графических файлов:.
        /// </summary>
        public static string order_info_text2 {
            get {
                return ResourceManager.GetString("order_info_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мы также можем принять макет в таких форматах как:.
        /// </summary>
        public static string order_info_text3 {
            get {
                return ResourceManager.GetString("order_info_text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если вы его не подготовили мы можем сделать это за Вас..
        /// </summary>
        public static string order_info_text4 {
            get {
                return ResourceManager.GetString("order_info_text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учитывайте что самостоятельная подготовка файла к лазерной порезке или гравировке может значительно ускорить срок выполнения Вашего заказа..
        /// </summary>
        public static string order_info_text5 {
            get {
                return ResourceManager.GetString("order_info_text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на все чертежи должны быть выполнены в масштабе 1:1.
        /// </summary>
        public static string order_info_text6 {
            get {
                return ResourceManager.GetString("order_info_text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на все элементы предназначенные для резки должны быть в кривых.
        /// </summary>
        public static string order_info_text7 {
            get {
                return ResourceManager.GetString("order_info_text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на чертеж изделия должен быть выполнен в тонких линиях.
        /// </summary>
        public static string order_info_text8 {
            get {
                return ResourceManager.GetString("order_info_text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на векторное изображение в файле для резки не должно содержать разомкнутых точек в замкнутых контурах, заливок, наложений контуров друг на друга, двойных линий и пересечений;.
        /// </summary>
        public static string order_info_text9 {
            get {
                return ResourceManager.GetString("order_info_text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо!.
        /// </summary>
        public static string order_thanks {
            get {
                return ResourceManager.GetString("order_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш заказ успешно оформлен. Мы свяжемся с вами в ближайшее время.
        /// </summary>
        public static string order_thanks_text {
            get {
                return ResourceManager.GetString("order_thanks_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цены на порезку различных материалов.
        /// </summary>
        public static string price_header {
            get {
                return ResourceManager.GetString("price_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обратите внимание, стоимость лазерной порезки высчитывается за метр погонный резки материала. Стоимость лазерной гравировки вычисляется за см²..
        /// </summary>
        public static string price_info {
            get {
                return ResourceManager.GetString("price_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛАЗЕРНАЯ ПОРЕЗКА: ФАНЕРА, МДФ, ДВП, OSB, КАРТОН.
        /// </summary>
        public static string price_table_1 {
            get {
                return ResourceManager.GetString("price_table_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛАЗЕРНАЯ ПОРЕЗКА АКРИЛА.
        /// </summary>
        public static string price_table_2 {
            get {
                return ResourceManager.GetString("price_table_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЛАЗЕРНАЯ ГРАВИРОВКА.
        /// </summary>
        public static string price_table_3 {
            get {
                return ResourceManager.GetString("price_table_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип материала.
        /// </summary>
        public static string price_table_3_col1 {
            get {
                return ResourceManager.GetString("price_table_3_col1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена, грн./см².
        /// </summary>
        public static string price_table_3_col2 {
            get {
                return ResourceManager.GetString("price_table_3_col2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Толщина материала, мм..
        /// </summary>
        public static string price_table_col_1 {
            get {
                return ResourceManager.GetString("price_table_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость, грн. за м.п. (до 100 м.).
        /// </summary>
        public static string price_table_col_2 {
            get {
                return ResourceManager.GetString("price_table_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость, грн. за м.п. (до 1000 м.).
        /// </summary>
        public static string price_table_col_3 {
            get {
                return ResourceManager.GetString("price_table_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость, грн. за м.п. (свыше 1000 м.).
        /// </summary>
        public static string price_table_col_4 {
            get {
                return ResourceManager.GetString("price_table_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить отзыв.
        /// </summary>
        public static string reviews_button {
            get {
                return ResourceManager.GetString("reviews_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оставить свой отзыв.
        /// </summary>
        public static string reviews_header {
            get {
                return ResourceManager.GetString("reviews_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string sort_header {
            get {
                return ResourceManager.GetString("sort_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От дорогих к дешёвым.
        /// </summary>
        public static string sort_high {
            get {
                return ResourceManager.GetString("sort_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От дешёвых к дорогим.
        /// </summary>
        public static string sort_low {
            get {
                return ResourceManager.GetString("sort_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новинки.
        /// </summary>
        public static string sort_new {
            get {
                return ResourceManager.GetString("sort_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Популярные.
        /// </summary>
        public static string sort_pop {
            get {
                return ResourceManager.GetString("sort_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акрил/Пластик.
        /// </summary>
        public static string table_3_row_1 {
            get {
                return ResourceManager.GetString("table_3_row_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фанера/Дерево.
        /// </summary>
        public static string table_3_row_2 {
            get {
                return ResourceManager.GetString("table_3_row_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камень.
        /// </summary>
        public static string table_3_row_3 {
            get {
                return ResourceManager.GetString("table_3_row_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кожа.
        /// </summary>
        public static string table_3_row_4 {
            get {
                return ResourceManager.GetString("table_3_row_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ткань.
        /// </summary>
        public static string table_3_row_5 {
            get {
                return ResourceManager.GetString("table_3_row_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цены на УФ Печать.
        /// </summary>
        public static string uv_price {
            get {
                return ResourceManager.GetString("uv_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоймость и вид материалов для УФ печати.
        /// </summary>
        public static string uv_subtitle {
            get {
                return ResourceManager.GetString("uv_subtitle", resourceCulture);
            }
        }
    }
}
